version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/EduPlatform.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=edplatform;Username=postgres;Password=postgres
      - Stripe__SecretKey=your_stripe_test_key
      - Stripe__PublishableKey=your_stripe_publishable_key
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=edplatform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: src/EduPlatform.Web/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data: 